site_name: Computer Science Reference

theme:
  favicon: 'images/favicon.png'
  name: 'material'
  palette:
    primary: 'Black'
    accent: 'indigo'
  font:
    text: 'Verdana'
    code: 'Consolas'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - type: 'github'
      link: 'https://github.com/codexpanse'
    - type: 'twitter'
      link: 'https://twitter.com/codexpanse'
    - type: 'youtube'
      link: 'https://youtube.com/codexpanse'
